name: "S3 Deploy CI/CD"

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: "Deploy S3 Changes"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials (Assume Role)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::415730361496:role/OIDC-Role-Role-IIhBuobxdcmm

    - name: Sync S3
      run: |
        aws s3 sync src s3://edisonlim.ca --delete --follow-symlinks

    - name: Invalidate CloudFront Cache
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: E38DU81BXX3NE6
        PATHS: "/*"
        AWS_REGION: "us-east-1"